### PR TITLE
refactor(tv): use global variables for tv domain and urls instead of hardcoded values

### PR DESCRIPTION
**Pull request by clins777**
### Overview

The goal of this PR is to move the TradingView domain and any URLs built on top of it to global variables

##### Pros

- Better maintainability: if in the future domain or url paths change we only need to modify a single file rather than finding and replacing all occurrences
- Better readability: urls now have human readable names and are shorter

##### Cons

- ~Variable is sometimes used in referer or origin (header) and in the endpoints so if those diverge at some point we wouldn't want to risk modifying one and breaking the other but I think this is already the case regardless of this PR~
- Let me know in the comments

##### Notes

I only refactored for the TradingView domain related URLs but we could do the same for the others as well ... I can do it on this PR if y'all agree or make another one later.

### CODE REVIEW

**Comment by clins777** [comment]
Ah ... I should of disable auto format on save 😓

**Comment by jwelmac** [comment]
Awesome move!

**Comment by clins777** [comment]
> Awesome move!

Thank you 🤝

**Comment by clins777** [comment]
@Mathieu2301 sorry to mention you directly. Could you have a quick look at this small PR?

**Pull request closed without merging**
